### ISSUE TITLE
Make spacing between shop items uniform.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Backpack-Shop#3]
![screenshot from 2016-07-04 12-22-12](https://cloud.githubusercontent.com/assets/1911594/16557766/f9d9b30e-41e1-11e6-922a-b6fca44e4feb.png)
On screens smaller than designed items break in unpredictable fashion causing problems with `nth-of-type` and similar. Instead margin should be applied to both left and right with half the current value.

**Comment by talrez11** [comment]
Will optimize uniform spacing on tablet version style
